### PR TITLE
Changed folder structure and Added remove-owner-references function

### PR DESCRIPTION
**Pull request by chaitanyab2311**
I am not very sure if its totally right. So I removed the owner resources field here but according to David do I need to purge the whole resource if metadata has ownerResources field. Please correct me if I did something wrong here.

### CODE REVIEW

**Comment by JonahSussman** [comment]
That's a lot of lines! I'll be sure to take a look tomorrow morning

**Comment by mundra-ankur** [comment]
> Filter "owned" resources - drop any resource that has an ownerReference

I think what he meant was to remove the resources which were created by some other resources (i.e. Pod via Deployment)
Similar to what we do in crane transform I guess

**Comment by chaitanyab2311** [comment]
Updated the function accordingly. This works now. Please have a look and suggest changes if any

**Comment by mundra-ankur** [comment]
Have you tested this on manifest which only has one resource ?
Can you please mention how you tested this ?

**Comment by chaitanyab2311** [comment]
If its only one resource then it removes that. I am not sure if that's the ideal way but then we wont encounter such condition as there will be at least one more resource that is owner resource. Tested this locally and using docker image. So there is this file in folder data on which I tested this

**Comment by mundra-ankur** [comment]
> If its only one resource then it removes that. I am not sure if that's the ideal way but then we wont encounter such condition as there will be at least one more resource that is owner resource. Tested this locally and using docker image. So there is this file in folder data on which I tested this

Can you try it once on a folder with multiple manifest and then try to delete one of the resource? Make sure each manifest has only one resource defined

**Comment by chaitanyab2311** [comment]
Yes tried it. It deletes the file with owner resource

**Review by mundra-ankur — APPROVED** [review]

**Pull request merged**
